version: 2.1

parameters:
  run_regression_per_connector:
    type: boolean
    default: false
  marker:
    type: string
    default: smoke

jobs:
  test:
    working_directory: ~/stepikqa
    docker: 
      - image: circleci/python:3.7.9
    steps:
      - checkout
      - run:
          name: Test
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip3 install -r requirements.txt
            pytest --env=Trex --tb=line
  run-check:
    working_directory: ~/stepikqa
    docker: 
      - image: circleci/python:3.7.9
    steps:
      - checkout
      - run:
          name: Check new code
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip3 install -r requirements.txt
            pytest -m << pipeline.parameters.marker >> --env=Trex --tb=line
workflows:
  version: 2
  commit:
    when: << pipeline.parameters.run_regression_per_connector >>
    jobs:
      - run-check
  cheduled-all-run:
    triggers:
      - schedule:
          cron: "0 9 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - test:
          context:
            - test-context
