version: 2.1

jobs:
  test:
    working_directory: ~/stepikqa
    docker: 
      - image: circleci/python:3.7.9
    steps:
      - checkout
      - run:
          name: Test
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip3 install -r requirements.txt
            pytest --env=Preview --td=line

workflows:
  main:
    jobs:
      - test:
          context:
            - test_context
